name: Golang CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Modules
        run: go mod tidy

      - name: Build
        run: go build -o ./app .
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_artifact
          path: ./app
          retention-days: 2

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: app_artifact

      - name: test 
        run: ./app < input.txt > result.txt
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: result.txt
          path: result
          retention-days: 2

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: app_artifact

      - name: Deploy to remote server 
        run: scp ./app root@38.0.101.76:/app && ssh root@38.0.101.76 "sudo systemctl restart app"

